### ISSUE TITLE
Output diff is B/W when running in CI/CD

### ISSUE THREAD

**Issue by Kampi** [INTI-CMNB/KiDiff#14]
Hi,

I want to use CI/CD to generate a diff between a `main` and a `feature` branch. The commands are tested in a Ubuntu VM and there I get colored outputs. The container is outputting B/W.

The workflow is shown below

```
name: Diff

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto_full:latest

    permissions:
      contents: write

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          path: modified
          submodules: recursive

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          path: original
          submodules: recursive

      - name: Create schematics diff
        run: |
          kicad-diff.py original/project/ZSWatch.kicad_sch modified/project/ZSWatch.kicad_sch --all_pages --output_dir diff-schematics --no_reader --keep_pngs

      - name: Create layout diff
        run: |
          kicad-diff.py original/project/ZSWatch.kicad_pcb modified/project/ZSWatch.kicad_pcb --all_pages --output_dir diff-layout --no_reader --keep_pngs

      - name: Upload Layout Diff
        uses: actions/upload-artifact@v4
        with:
          name: "diff-layout-master-${{ github.ref_name }}"
          path: diff-layout
          if-no-files-found: ignore

      - name: Upload Schematics Diff
        uses: actions/upload-artifact@v4
        with:
          name: "diff-schematics-master-${{ github.ref_name }}"
          path: diff-schematics
          if-no-files-found: ignore
```

The output can be viewed [here](https://github.com/Kampi/ZSWatch-HW/actions/runs/11650838162/job/32440053316).

How can I change it back to colored output?
