### ISSUE TITLE
[BUG] Problems when page size is different

### ISSUE THREAD

**Issue by Harmhongerkamp** [INTI-CMNB/KiDiff#5]
**What do you want to achieve?**
i have some project that contain schematics which are A3 or A2 sizes, with multiple variants. I want to diff them between variants and various commits. 
this works whit projects that contain A4 sized schematics, but not with A2 and A3 sized ones. 

**Do you have some PCB/Schematic to use as example?**
yes, see attached

**Do you have some configuration file (.kibot.yaml) that you are using?**
You can attach it or paste the content in the following section:
```yaml
kibot:
  version: 1
outputs:
  # Documentation -------------------------------------------------------------
  - name: 'schematic'
    comment: "Export schematic as pdf"
    type: pdf_sch_print
    dir: documentation
  # ---------------------------------------------------------------------------
  - name: "sch_variant"
    type: sch_variant
    comment: "Generate sch variant for other outputs to use"
    dir: /tmp

  - name: "schdiff local<>master"
    type: diff
    dir: documentation/diffs
    options: 
      output: '%f-%v-schdiff-pr.%x'
      new: "sch_variant"
      new_type: output
      old: master
      old_type: git
      pcb: false
      force_checkout: true
      only_first_sch_page: false
    priority: 10
  #TODO
  - name: "schdiff local<>last"
    type: diff
    comment: "Generate diff"
    dir: documentation/diffs
    options: 
      output: '%f-%v-schdiff-commit.%x'
      new: "sch_variant"
      new_type: output
      old: "HEAD~"
      old_type: git
      pcb: false
      force_checkout: true
      only_first_sch_page: false
    priority: 10
```

**Environment (please complete the following information):**
Where are you running KiBot:
- Using a docker image? 
  - `kicad6_auto:latest` with git-lfs added.
- Using a desktop system? Which OS, distro and version?
  - ubuntu 20-04 lts. (probably not relevant since is use a docker image"
**Additional context**
Add any other context about your setup/project.
[example_project.zip](https://github.com/INTI-CMNB/KiBot/files/11091217/example_project.zip)

debug output (ran kibot with -vvv)`
<pre><font color="#06989A"><b>DEBUG:Executing: /usr/bin/kicad-diff.py -vvv --no_reader --new_file_hash sch511fa71940ad1dc0c48b519b4f23dad68ea83dbb --old_file_hash sch146e35e6fa09bf0d7d78442f1a035c690786e586 --cache_dir /tmp/tmpjz2s6ro6 --output_dir /tmp/kibot_build/main/FULL/build/documentation/diffs --output_name main-FULL-schdiff-local.pdf --diff_mode red_green --fuzz 5 --no_exist_check --all_pages /tmp/tmpdf82snpw.kicad_sch /tmp/main.kicad_sch (kibot - kiplot.py:159)</b></font>
<p style="color:Red";><b>ERROR:Running [&apos;/usr/bin/kicad-diff.py&apos;, &apos;-vvv&apos;, &apos;--no_reader&apos;, &apos;--new_file_hash&apos;, &apos;sch511fa71940ad1dc0c48b519b4f23dad68ea83dbb&apos;, &apos;--old_file_hash&apos;, &apos;sch146e35e6fa09bf0d7d78442f1a035c690786e586&apos;, &apos;--cache_dir&apos;, &apos;/tmp/tmpjz2s6ro6&apos;, &apos;--output_dir&apos;, &apos;/tmp/kibot_build/main/FULL/build/documentation/diffs&apos;, &apos;--output_name&apos;, &apos;main-FULL-schdiff-local.pdf&apos;, &apos;--diff_mode&apos;, &apos;red_green&apos;, &apos;--fuzz&apos;, &apos;5&apos;, &apos;--no_exist_check&apos;, &apos;--all_pages&apos;, &apos;/tmp/tmpdf82snpw.kicad_sch&apos;, &apos;/tmp/main.kicad_sch&apos;] returned 6 (kibot - out_diff.py:460)</b></p>
<font color="#06989A"><b>DEBUG:- Output from command: DEBUG:kicad-diff.py:/tmp/tmpdf82snpw.kicad_sch SHA1 is sch146e35e6fa09bf0d7d78442f1a035c690786e586</b></font>
<font color="#06989A"><b>DEBUG:kicad-diff.py:/tmp/main.kicad_sch SHA1 is sch511fa71940ad1dc0c48b519b4f23dad68ea83dbb</b></font>
<font color="#06989A"><b>DEBUG:kicad-diff.py:Cache dir: /tmp/tmpjz2s6ro6</b></font>
<font color="#06989A"><b>DEBUG:kicad-diff.py:Output dir: /tmp/kibot_build/main/FULL/build/documentation/diffs</b></font>
<font color="#06989A"><b>DEBUG:kicad-diff.py:Cache for /tmp/tmpdf82snpw.kicad_sch will be /tmp/tmpjz2s6ro6/sch146e35e6fa09bf0d7d78442f1a035c690786e586</b></font>
<font color="#06989A"><b>INFO:kicad-diff.py:cache dir for `/tmp/tmpdf82snpw.kicad_sch` already exists</b></font>
<font color="#06989A"><b>DEBUG:kicad-diff.py:Using cached schematic</b></font>
<font color="#06989A"><b>DEBUG:kicad-diff.py:Cache for /tmp/main.kicad_sch will be /tmp/tmpjz2s6ro6/sch511fa71940ad1dc0c48b519b4f23dad68ea83dbb</b></font>
<font color="#06989A"><b>INFO:kicad-diff.py:cache dir for `/tmp/main.kicad_sch` already exists</b></font>
<font color="#06989A"><b>DEBUG:kicad-diff.py:Using cached schematic</b></font>
<font color="#06989A"><b>DEBUG:kicad-diff.py:/tmp/tmpjz2s6ro6/sch146e35e6fa09bf0d7d78442f1a035c690786e586/Schematic_root.pdf already converted to PNG</b></font>
<font color="#06989A"><b>DEBUG:kicad-diff.py:/tmp/tmpjz2s6ro6/sch511fa71940ad1dc0c48b519b4f23dad68ea83dbb/Schematic_root.pdf already converted to PNG</b></font>
<font color="#06989A"><b>INFO:kicad-diff.py:Creating diff for Schematic_root</b></font>
<font color="#06989A"><b>DEBUG:kicad-diff.py:Executing: [&apos;bash&apos;, &apos;-c&apos;, &apos;( convert &quot;/tmp/tmpjz2s6ro6/sch511fa71940ad1dc0c48b519b4f23dad68ea83dbb/Schematic_root.png&quot; miff:- ; convert &quot;/tmp/tmpjz2s6ro6/sch146e35e6fa09bf0d7d78442f1a035c690786e586/Schematic_root.png&quot; miff:- ) | convert - \\( -clone 0-1 -compose darken -composite \\)  -font helvetica -pointsize 30 -draw &quot;text 10,30 \&apos;/\&apos;&quot;  -channel RGB -combine &quot;/tmp/kibot_build/main/FULL/build/documentation/diffs/diff-Schematic_root0.png&quot;&apos;]</b></font>
<font color="#06989A"><b>DEBUG:kicad-diff.py:Running [&apos;bash&apos;, &apos;-c&apos;, &apos;( convert &quot;/tmp/tmpjz2s6ro6/sch511fa71940ad1dc0c48b519b4f23dad68ea83dbb/Schematic_root.png&quot; miff:- ; convert &quot;/tmp/tmpjz2s6ro6/sch146e35e6fa09bf0d7d78442f1a035c690786e586/Schematic_root.png&quot; miff:- ) | convert - \\( -clone 0-1 -compose darken -composite \\)  -font helvetica -pointsize 30 -draw &quot;text 10,30 \&apos;/\&apos;&quot;  -channel RGB -combine &quot;/tmp/kibot_build/main/FULL/build/documentation/diffs/diff-Schematic_root0.png&quot;&apos;] returned 1</b></font>
<font color="#06989A"><b>DEBUG:kicad-diff.py:- StdOut from command: convert-im6.q16: images are not the same size `/tmp/magick-zYpjF9Fi_NNdTMeLo77p_YK7tXBskfjw&apos; @ error/channel.c/CombineImages/128.</b></font>

<font color="#06989A"><b>ERROR:kicad-diff.py:Failed to create diff /tmp/kibot_build/main/FULL/build/documentation/diffs/diff-Schematic_root0.png</b></font>
<font color="#06989A"><b> (kibot - out_diff.py:462)</b></font></pre>
